server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
      
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**,/users
      
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
          - Path=/rating/**,/ratings/**
          
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
          - Method=POST,GET,PUT,DELETE
    
  config:
    import: configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka